AWSTemplateFormatVersion: 2010-09-09
Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: [ ajla.ng ]
        DefaultCacheBehavior:
          Compress: true
          DefaultTTL: 60
          ForwardedValues:
            Cookies: { Forward: none }
            QueryString: false
          TargetOriginId: OriginProduction
          ViewerProtocolPolicy: allow-all
        Enabled: true
        Origins:
        - CustomOriginConfig: { OriginProtocolPolicy: https-only }
          DomainName: !Sub
            - ${RestApiGithub}.execute-api.${AWS::Region}.amazonaws.com
            - RestApiGithub: !Ref RestApiGithub
          Id: OriginProduction
          OriginPath: /production
        ViewerCertificate: { CloudFrontDefaultCertificate: true }
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ajla.ng

